config/routes.rb
Rails.application.routes.draw do

  root to: "tweets#index"
  
  devise_for :users
  
  resources :tweets do
    resources :replies, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers
    end
  end

  resources :tags, only: [:index, :show]

  namespace :admin do
    resources :tweets
    resources :users
    root "tweets#index"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :tweet
  belongs_to :user
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"

end

app/models/reply.rb
class Reply < ApplicationRecord

  belongs_to :user
  belongs_to :tweet
  validates :comment, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :content, presence: true, uniqueness: true
  has_many :tags_tweets
  has_many :tweets, through: :tags_tweets
end

app/models/tags_tweet.rb
class TagsTweet < ApplicationRecord
  belongs_to :tag
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  belongs_to :user
  validates :post, presence: true, length: { maximum: 140 }
  has_many :likes
  has_many :replies

  has_many :tags_tweets
  has_many :tags, through: :tags_tweets

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    self.role == "admin"
  end

  has_many :tweets
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
  mount_uploader :image, ImageUploader
  has_many :likes
  has_many :replies


  has_many :active_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :passive_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy

  has_many :followings, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower

  

end

app/controllers/admin/tweets_controller.rb
class Admin::TweetsController < Admin::BaseController

  before_action :set_tweet, only:  [:destroy]

  def index
    @tweets = Tweet.all
  end

  def destroy
    @tweet.destroy
    flash[:alert] = "Tweet was deleted"
    redirect_to admin_tweets_path
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
		@like = Like.all
		@tweet = Tweet.find(params[:tweet_id])
		tweet_likes = @tweet.likes.build
		tweet_likes.user = current_user
		tweet_likes.save

	end

	def destroy
		@like = Like.all
		@tweet = Tweet.find(params[:tweet_id])
		like = Like.find(params[:id])
		like.destroy

	end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    new_follow = Relationship.new
		new_follow.update(follower_id: current_user.id, following_id: @user.id)
  end

  def destroy
    @user = User.find(params[:user_id])
		unfollow = Relationship.find(params[:id])
		unfollow.destroy
  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @reply = @tweet.replies.build(reply_params)
    @reply.user = current_user
    @reply.save!
    redirect_to tweet_path(@tweet)
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @reply = Reply.find(params[:id])

    if current_user.admin?
      @reply.destroy
      redirect_to tweet_path(@tweet)
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:comment)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
    @user = current_user
  end

  def show
    @tag = Tag.find(params[:id])
    @user = current_user
    @tags = Tag.all
    @user_followers = @user.followers.limit(10)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :set_tweet, only:  [:show]

  def index
    @tweet = Tweet.new
    @tweets = Tweet.all
    @user_tweet = current_user.tweets.order("created_at DESC")
    @user = current_user
    @user_following = @user.followings
    @user_followers = @user.followers.limit(10)
    @tags = Tag.all
  end

   def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      @tag_array = @tweet.post.scan(/#\w+\b/)
      unless @tag_array == []
        @tag_array.each do |tag|
          @tag = Tag.find_or_create_by(content: tag)
          @tag.save
          @tweet.tags << @tag
        end
      end
      redirect_to tweets_path
    else
      redirect_to tweets_path
    end
    end

  def show
    @reply = Reply.new
  end

  private

  def tweet_params
    params.require(:tweet).permit(:post)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only:  [:show, :edit, :update]

  def index
    @users = User.all
    @user = current_user
    @user_following = @user.followings
    @user_followers = @user.followers.limit(10)
    @tags = Tag.all
  end

  def show
    @user_tweet = @user.tweets
    @user_following = @user.followings
    @user_followers = @user.followers.limit(10)
    @tags = Tag.all
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User profile was successfully updated"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "User profile was failed to update"
      render :edit
    end
  end

  def followings
    @user  = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :bio, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/admin/tweets_helper.rb
module Admin::TweetsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user?(user)
    user == current_user
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/tweets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>All Tweets</h1>
      <div>
        <%= link_to 'Tweets', admin_tweets_path %> |
        <%= link_to 'Users', admin_users_path %>
      </div>
      <br>
      <table class="table table-light">
        <thead>
          <tr>
            <th scope="col">Tweet</th>
            <th scope="col">Username</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @tweets.each do |tweet| %>
          <tr>
            <td><%= tweet.post %></td>
            <td><%= tweet.user.username %></td>
            <td>
              <%= link_to 'Delete', admin_tweet_path(tweet), method: :delete, data: {confirm:"Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
          <%= image_tag @user.image, class: "img-fluid rounded mx-auto" %>
          <h5><%= @user.name.capitalize %></h5>
          <h7 class="text-colour">@<%= @user.username %></h7>
          <div>Joined <%= @user.created_at.strftime("%B %Y") %></div>
          <% if @user.tweets.count <= 1 %>
            <div><%= @user.tweets.count %> tweet</div>
          <% else %>
            <div><%= @user.tweets.count %> tweets</div>
          <% end %>
          <br>
          <section class="stats">
            <%= render 'shared/stats' %>
          </section>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h5>Trending</h5>
          <% @tags.each do |tag| %>
            <p><%= link_to tag.content, tag_path(tag) %></p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6 mt-3">
      <%= form_for [@tweet] do |f| %>
      <div class="form-group">
      <%= f.text_area :post, class: 'form-control', rows: 1, placeholder: "What's happening?", maxlength: 140, id: 'textbox' %>
       <div align="right"><span id="chars">140</span> characters remaining</div>
      </div>
      <div class="form-group d-flex justify-content-end">
        <%= f.submit "Tweet", class: 'btn btn-primary', id: 'submitButtonId' %>
      </div>
      <% end %>
      <% @user_tweet.each do |tweet| %>
      <div class="card">
        <div class="card-body">
          <small><b><%= @user.name %></b> <i>@<%= link_to @user.username, user_path(@user) %></i> - <%= distance_of_time_in_words(tweet.created_at, Time.now)%> ago</small>
          <p><%= tweet.post %></p>
            <%=  link_to (icon("far", "comment")), tweet_path(tweet) %> <%= tweet.replies.count %>&nbsp;&nbsp;&nbsp;&nbsp;
          <div id="likes">
            <div id="likes-buttons_<%= tweet.id %>">
              <%= render "likes_buttons", tweet: tweet %>
            </div>
          </div>
          <div id="counters">
            <div id="id-counter_<%= tweet.id %>">
              <%= render "counter", tweet: tweet %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <% @user_following.each do |following| %>
        <% following.tweets.each do |tweet| %>
          <div class="card">
            <div class="card-body">
              <small><b><%= following.name %></b> <i>@<%= link_to following.username, user_path(following) %></i> - <%= distance_of_time_in_words(tweet.created_at, Time.now)%> ago</small>
              <%=  link_to (icon("far", "comment")), tweet_path(tweet) %> <%= tweet.replies.count %>&nbsp;&nbsp;&nbsp;&nbsp;
              <div id="likes">
                <div id="likes-buttons_<%= tweet.id %>">
                  <%= render "likes_buttons", tweet: tweet %>
                </div>
              </div>
              <div id="counters">
                <div id="id-counter_<%= tweet.id %>">
                  <%= render "counter", tweet: tweet %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
          <p>Your 10 Followers</p>
          <% @user_followers.each do |follower| %></p>
            <p><b><%= follower.name %></b> <i>@<%= link_to follower.username, user_path(follower) %></i></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <small><b><%= @tweet.user.name %></b> <i>@<%= @tweet.user.username %></i> Created <%= distance_of_time_in_words(@tweet.created_at, Time.now)%> ago</small>
          <h3><%= @tweet.post %></h3>
        </div>
      </div>
      <br>
      <h4>Replies</h4>
    </div>
    <div class="col-md-12">
      <% @tweet.replies.each do |reply| %>
      <div class="card">
        <div class="card-body">
        <small><b><%= reply.user.name %></b> <i>@<%= reply.user.username %></i> Created <%= distance_of_time_in_words(reply.created_at, Time.now)%> ago</small>
          <p><%= reply.comment %></p>
            <% if current_user.admin? %>
              <%= link_to "Delete", tweet_reply_path(@tweet, reply), method: :delete %>
            <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <div class="col-md-12">
      <%= form_for [@tweet, @reply] do |f| %>
      <div class="form-group">
        <%= f.text_area :comment, class: "form-control", rows: 1, placeholder: "Tweet your reply",  maxlength: 140, id: 'textbox' %>
        <div align="right"><span id="chars">140</span> characters remaining</div>
      </div>
      <div class="form-group">
        <%= f.submit "Reply", class: "btn btn-primary", id: 'submitButtonId' %>
        <%= f.button "Cancel", type: :reset, class: "btn btn-outline-dark" %>
      </div>
    <% end %>
    </div>
  </div>
</div>