config/routes.rb
Rails.application.routes.draw do

  root to: "tweets#index"
  
  devise_for :users
  
  resources :tweets do
    resources :replies, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers
    end
  end

  resources :tags, only: [:index, :show]

  namespace :admin do
    resources :tweets
    resources :users
    root "tweets#index"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :tweet
  belongs_to :user
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"

end

app/models/reply.rb
class Reply < ApplicationRecord

  belongs_to :user
  belongs_to :tweet
  validates :comment, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :content, presence: true, uniqueness: true
  has_many :tags_tweets
  has_many :tweets, through: :tags_tweets
end

app/models/tags_tweet.rb
class TagsTweet < ApplicationRecord
  belongs_to :tag
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  belongs_to :user
  validates :post, presence: true, length: { maximum: 140 }
  has_many :likes
  has_many :replies

  has_many :tags_tweets
  has_many :tags, through: :tags_tweets

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    self.role == "admin"
  end

  has_many :tweets
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
  mount_uploader :image, ImageUploader
  has_many :likes
  has_many :replies


  has_many :active_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :passive_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy

  has_many :followings, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower

  

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.all
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
		@like = Like.all
		@tweet = Tweet.find(params[:tweet_id])
		tweet_likes = @tweet.likes.build
		tweet_likes.user = current_user
		tweet_likes.save

	end

	def destroy
		@like = Like.all
		@tweet = Tweet.find(params[:tweet_id])
		like = Like.find(params[:id])
		like.destroy

	end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    new_follow = Relationship.new
		new_follow.update(follower_id: current_user.id, following_id: @user.id)
  end

  def destroy
    @user = User.find(params[:user_id])
		unfollow = Relationship.find(params[:id])
		unfollow.destroy
  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @reply = @tweet.replies.build(reply_params)
    @reply.user = current_user
    @reply.save!
    redirect_to tweet_path(@tweet)
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @reply = Reply.find(params[:id])

    if current_user.admin?
      @reply.destroy
      redirect_to tweet_path(@tweet)
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:comment)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
    @user = current_user
  end

  def show
    @tag = Tag.find(params[:id])
    @user = current_user
    @tags = Tag.all
    @user_followers = @user.followers.limit(10)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :set_tweet, only:  [:show]

  def index
    @tweet = Tweet.new
    @tweets = Tweet.all
    @user_tweet = current_user.tweets.order("created_at DESC")
    @user = current_user
    @user_following = @user.followings
    @user_followers = @user.followers.limit(10)
    @tags = Tag.all
  end

   def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      @tag_array = @tweet.post.scan(/#\w+\b/)
      unless @tag_array == []
        @tag_array.each do |tag|
          @tag = Tag.find_or_create_by(content: tag)
          @tag.save
          @tweet.tags << @tag
        end
      end
      redirect_to tweets_path
    else
      redirect_to tweets_path
    end
    end

  def show
    @reply = Reply.new
  end

  private

  def tweet_params
    params.require(:tweet).permit(:post)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only:  [:show, :edit, :update]

  def index
    @users = User.all
    @user = current_user
    @user_following = @user.followings
    @user_followers = @user.followers.limit(10)
    @tags = Tag.all
  end

  def show
    @user_tweet = @user.tweets
    @user_following = @user.followings
    @user_followers = @user.followers.limit(10)
    @tags = Tag.all
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User profile was successfully updated"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "User profile was failed to update"
      render :edit
    end
  end

  def followings
    @user  = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :bio, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/admin/tweets_helper.rb
module Admin::TweetsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user?(user)
    user == current_user
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>All Tweets</h1>
      <div>
        <%= link_to 'Tweets', admin_tweets_path %> |
        <%= link_to 'Users', admin_users_path %>
      </div>
      <br>
      <table class="table table-light">
        <thead>
          <tr>
            <th scope="col">User</th>
            <th scope="col">Tweet Count</th>
            <th scope="col">Following Count</th>
            <th scope="col">Followers Count</th>
            <th scope="col">Like Count</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.tweets.count %></td>
            <td><%= user.followings.count %></td>
            <td><%= user.followers.count %></td>
            <td><%= user.likes.count %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/_counter.html.erb
<%= tweet.likes.count %>

app/views/users/_follow_form.html.erb
<% if current_relationship = Relationship.find_by(follower_id: current_user.id, following_id: user.id) %>

		<%= link_to user_relationship_path(user_id: user.id, id: current_relationship.id), method: :delete, class: 'btn btn-primary btn-unfollow', remote: true do %>
		 <span class="before">Following</span><span class="after">Unfollow</span>
		 <% end %>

<% else %><%= link_to "Follow", user_relationships_path(user), method: :post, class: 'btn btn-outline-primary', remote: true %>

<% end %>

app/views/users/_followers_count.html.erb
<p><strong><%= user.followings.count %></strong> following <strong><%= user.followers.count %></strong> followers</p>

app/views/users/_likes_buttons.html.erb
<% if tweet.likes.find_by(user_id: current_user.id)%>
    <% current_like = tweet.likes.find_by(user_id: current_user.id)%>
  <%= link_to icon("fas", "heart"), tweet_like_path(tweet_id: tweet.id, id: current_like.id), method: :delete, remote: true %>
<% else %>
  <%= link_to icon("far", "heart"), tweet_likes_path(tweet_id: tweet.id), method: :post, remote: true %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-6 offset-md-3">

      <h3>Edit Profile</h3>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :username, "Username" %>
          <%= f.text_field :username, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :bio, "Profile" %>
          <%= f.text_area :bio, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :image, "Picture" %>
          <%= image_tag @user.image if @user.image? %>
          <%= f.file_field :image %>
        </div>

        <div class="form-group">
          <%= f.submit "Update", class: "btn btn-primary" %>
          <%= link_to "Cancel", user_path(@user), class: "btn btn-outline-dark" %>
        </div>
      <% end %>

    </div>

  </div>
</div>

app/views/users/followers.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
          <%= image_tag @user.image, class: "img-fluid rounded mx-auto" %>
          <h5><%= @user.name.capitalize %></h5>
          <h7 class="text-colour">@<%= @user.username %></h7>
          <div>Joined <%= @user.created_at.strftime("%B %Y") %></div>
          <% if @user.tweets.count <= 1 %>
            <div><%= @user.tweets.count %> tweet</div>
          <% else %>
            <div><%= @user.tweets.count %> tweets</div>
          <% end %>
          <br>
          <section class="stats">
            <%= render 'shared/stats' %>
          </section>
        </div>
      </div>
    </div>
    <div class="col-md-6 mt-3">
      <% @users.each do |follower| %>
        <div class="card">
          <div class="card-body">
            <small><b><%= follower.name %></b> <i>@<%= link_to follower.username, user_path(follower) %></i></small>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
          <%= image_tag @user.image, class: "img-fluid rounded mx-auto" %>
          <h5><%= @user.name.capitalize %></h5>
          <h7 class="text-colour">@<%= @user.username %></h7>
          <div>Joined <%= @user.created_at.strftime("%B %Y") %></div>
          <% if @user.tweets.count <= 1 %>
            <div><%= @user.tweets.count %> tweet</div>
          <% else %>
            <div><%= @user.tweets.count %> tweets</div>
          <% end %>
          <br>
          <section class="stats">
            <%= render 'shared/stats' %>
          </section>
        </div>
      </div>
    </div>
    <div class="col-md-6 mt-3">
      <% @users.each do |following| %>
        <div class="card">
          <div class="card-body">
            <small><b><%= following.name %></b> <i>@<%= link_to following.username, user_path(following) %></i></small>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
          <%= image_tag @user.image, class: "img-fluid rounded mx-auto" %>
          <h5><%= @user.name.capitalize %></h5>
          <h7 class="text-colour">@<%= @user.username %></h7>
          <div>Joined <%= @user.created_at.strftime("%B %Y") %></div>
          <% if @user.tweets.count <= 1 %>
            <div><%= @user.tweets.count %> tweet</div>
          <% else %>
            <div><%= @user.tweets.count %> tweets</div>
          <% end %>
          <br>
            <section class="stats">
              <%= render 'shared/stats' %>
            </section>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h5>Trending</h5>
          <% @tags.each do |tag| %>
            <p><%= link_to tag.content, tag_path(tag) %></p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6 mt-3">
    <% @users.each do |user| %>
      <div class="card">
        <div class="card-body">
          <small><b><%= user.name %></b> <i>@<%= link_to user.username, user_path(user) %></i></small>
          <p>Latest Tweet: <%= user.tweets.last.try(:post) %></p>

            <div id="followers_<%= user.id %>">
              <p><%= render partial: 'followers_count', locals: {user: user} %></p>
            </div>

          <% if user != current_user %>
            <div id="follow_<%= user.id %>">
              <p><%= render partial: 'follow_form', locals: {user: user} %></p>
            </div>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
          <p>Your 10 Followers</p>
          <% @user_followers.each do |follower| %></p>
            <p><b><%= follower.name %></b> <i>@<%= link_to follower.username, user_path(follower) %></i></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
          <%= image_tag @user.image, class: "img-fluid rounded mx-auto" %>
          <h5><%= @user.name.capitalize %></h5>
          <h7 class="text-colour">@<%= @user.username %></h7>
          <div>Joined <%= @user.created_at.strftime("%B %Y") %></div>
          <% if @user.tweets.count <= 1 %>
            <div><%= @user.tweets.count %> tweet</div>
          <% else %>
            <div><%= @user.tweets.count %> tweets</div>
          <% end %>
          <% if @user != current_user %>
            <div id="follow_<%= @user.id %>">
              <p><%= render partial: 'follow_form', locals: {user: @user} %></p>
            </div>
          <% end %>
          <div><%= simple_format @user.bio %></div>
          <br>
            <section class="stats">
              <%= render 'shared/stats' %>
            </section>
            <br>
          <% if @user.email == current_user.email %>
            <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-outline-primary" %>
          <% end %>
        </div>
        <br>
      </div>
      <div class="card">
        <div class="card-body">
          <h5>Trending</h5>
          <% @tags.each do |tag| %>
            <p><%= link_to tag.content, tag_path(tag) %></p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6 mt-3">
    <% @user_tweet.each do |tweet| %>
      <div class="card">
        <div class="card-body">
          <small><b><%= @user.name %></b> <i>@<%= @user.username %></i> Created <%= distance_of_time_in_words(tweet.created_at, Time.now)%> ago</small>
          <p><%= tweet.post %></p>
          <%=  link_to (icon("far", "comment")), tweet_path(tweet) %> <%= tweet.replies.count  %>&nbsp;&nbsp;&nbsp;&nbsp;
          <div id="likes">
            <div id="likes-buttons_<%= tweet.id %>">
              <%= render "likes_buttons", tweet: tweet %>
            </div>
          </div>
          <div id="counters">
            <div id="id-counter_<%= tweet.id %>">
              <%= render "counter", tweet: tweet %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
          <p><%= @user.name.capitalize %>'s 10 Followers</p>
          <% @user_followers.each do |follower| %></p>
            <p><b><%= follower.name %></b> <i>@<%= link_to follower.username, user_path(follower) %></i></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>