config/routes.rb
Rails.application.routes.draw do

  root to: "tweets#index"
  
  devise_for :users
  
  resources :tweets do
    resources :replies, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers
    end
  end

  resources :tags, only: [:index, :show]

  namespace :admin do
    resources :tweets
    resources :users
    root "tweets#index"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :tweet
  belongs_to :user
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"

end

app/models/reply.rb
class Reply < ApplicationRecord

  belongs_to :user
  belongs_to :tweet
  validates :comment, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :content, presence: true, uniqueness: true
  has_many :tags_tweets
  has_many :tweets, through: :tags_tweets
end

app/models/tags_tweet.rb
class TagsTweet < ApplicationRecord
  belongs_to :tag
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  belongs_to :user
  validates :post, presence: true, length: { maximum: 140 }
  has_many :likes
  has_many :replies

  has_many :tags_tweets
  has_many :tags, through: :tags_tweets

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    self.role == "admin"
  end

  has_many :tweets
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
  mount_uploader :image, ImageUploader
  has_many :likes
  has_many :replies


  has_many :active_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :passive_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy

  has_many :followings, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower

  

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
		@like = Like.all
		@tweet = Tweet.find(params[:tweet_id])
		tweet_likes = @tweet.likes.build
		tweet_likes.user = current_user
		tweet_likes.save

	end

	def destroy
		@like = Like.all
		@tweet = Tweet.find(params[:tweet_id])
		like = Like.find(params[:id])
		like.destroy

	end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @reply = @tweet.replies.build(reply_params)
    @reply.user = current_user
    @reply.save!
    redirect_to tweet_path(@tweet)
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @reply = Reply.find(params[:id])

    if current_user.admin?
      @reply.destroy
      redirect_to tweet_path(@tweet)
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:comment)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
    @user = current_user
  end

  def show
    @tag = Tag.find(params[:id])
    @user = current_user
    @tags = Tag.all
    @user_followers = @user.followers.limit(10)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :set_tweet, only:  [:show]

  def index
    @tweet = Tweet.new
    @tweets = Tweet.all
    @user_tweet = current_user.tweets.order("created_at DESC")
    @user = current_user
    @user_following = @user.followings
    @user_followers = @user.followers.limit(10)
    @tags = Tag.all
  end

   def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      @tag_array = @tweet.post.scan(/#\w+\b/)
      unless @tag_array == []
        @tag_array.each do |tag|
          @tag = Tag.find_or_create_by(content: tag)
          @tag.save
          @tweet.tags << @tag
        end
      end
      redirect_to tweets_path
    else
      redirect_to tweets_path
    end
    end

  def show
    @reply = Reply.new
  end

  private

  def tweet_params
    params.require(:tweet).permit(:post)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only:  [:show, :edit, :update]

  def index
    @users = User.all
    @user = current_user
    @user_following = @user.followings
    @user_followers = @user.followers.limit(10)
    @tags = Tag.all
  end

  def show
    @user_tweet = @user.tweets
    @user_following = @user.followings
    @user_followers = @user.followers.limit(10)
    @tags = Tag.all
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User profile was successfully updated"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "User profile was failed to update"
      render :edit
    end
  end

  def followings
    @user  = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :bio, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user?(user)
    user == current_user
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter Clone</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicons/favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light" id="bg-color">
      <% if current_user %>
        <span class="navbar-item">Hi, <%= current_user.name.capitalize %>!</span>&nbsp&nbsp&nbsp&nbsp
        <span><%= link_to "Home", root_path, class: "navbar-brand" %></span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
            <% if current_user.admin? %>
              <li class="nav-item"><%= link_to('Admin', admin_tweets_path, class: 'nav-link') %></li>
            <% end %>
            <li class="nav-item navbar-nav"><%= link_to('Profile', user_path(current_user), class: 'nav-link') %></li> 
            <li class="nav-item navbar-nav"><%= link_to('Users', users_path(@users), class: 'nav-link') %></li> 
            <li class="nav-item navbar-nav"><%= link_to('Log out', destroy_user_session_path, method: :delete, class: 'nav-link') %></li> 
            <li class="nav-item navbar-nav"><%= link_to('Change password', edit_user_registration_path , class: 'nav-link') %></li>
          <% else %>
            <li class="navbar-nav nav-item"><%= link_to('Register', new_user_registration_path, class: 'nav-link') %></li> 
            <li class="navbar-nav nav-item"><%= link_to('Log in', new_user_session_path, class: 'nav-link') %></li>
        </ul>
      </div>
      <% end %>
    </nav>

    <% if flash[:notice] %>
      <div class="container-fluid">
        <div class="row">
          <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
            <%= notice %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="container-fluid">
        <div class="row">
          <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
            <%= alert %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_stats.html.erb
<div class="stats">
  <a href="<%= followings_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>